/*	Project Euler
	Probleme n°2

		Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
			1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

		By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

#include <stdio.h>
#include <stdlib.h>

int
main()
{
	int 	term				= 1,
			tmpTerm			= 0,
			previousTerm 	= 0 ;
	long int sum 	= 0 ;

	while (sum < 4000000)
	{
			tmpTerm = term ;
			term = term + previousTerm ;
			previousTerm = tmpTerm ;

			printf("%d\t\t", term) ;
			if (term%2 == 0)
				sum += term ;
			//printf("i = %d\t", i) ;
	}

	printf("\nsum = %ld\n", sum) ;

	return EXIT_SUCCESS ;
}
